---
tasks:
- name: No Tasks for features/borrow
  scripts:
    test:
      body: echo OK
- name: spec/features/borrow/model_list.feature:115
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/borrow/load.rb spec/features/borrow/model_list.feature:115
- name: spec/features/borrow/model_list.feature:168
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/borrow/load.rb spec/features/borrow/model_list.feature:168
- name: spec/features/borrow/model_list.feature:28
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/borrow/load.rb spec/features/borrow/model_list.feature:28
- name: spec/features/borrow/model_list.feature:84
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/borrow/load.rb spec/features/borrow/model_list.feature:84
