---
tasks:
- name: features/manage/acknowledge/add_item.feature:16
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/acknowledge/add_item.feature:16
- name: features/manage/acknowledge/add_item.feature:42
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/acknowledge/add_item.feature:42
- name: features/manage/acknowledge/delete_lines.feature:16
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/acknowledge/delete_lines.feature:16
- name: features/manage/calendar.feature:18
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/calendar.feature:18
- name: features/manage/displaying_problems.feature:22
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/displaying_problems.feature:22
- name: features/manage/displaying_problems.feature:76
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/displaying_problems.feature:76
- name: features/manage/hand_over/edit_reservation.feature:40
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/hand_over/edit_reservation.feature:40
- name: features/manage/inventory/inventory.feature:219
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/inventory/inventory.feature:219
- name: features/manage/lending/lending.feature:155
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/lending/lending.feature:155
- name: features/manage/lending/lending.feature:44
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/lending/lending.feature:44
- name: features/manage/lending/lending.feature:61
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/lending/lending.feature:61
- name: features/manage/not_logged_in_information.feature:9
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/not_logged_in_information.feature:9
- name: features/manage/order/contract.feature:84
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/order/contract.feature:84
- name: features/manage/software/search_for_software.feature:26
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/software/search_for_software.feature:26
- name: features/manage/take_back/edit_take_back_end_date.feature:17
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/take_back/edit_take_back_end_date.feature:17
- name: features/manage/verification.feature:31
  scripts:
    test:
      body: |-
        #!/usr/bin/env bash
        set -euo pipefail
        mkdir -p log
        unset PGPORT; unset PGUSER; export PGUSER=${PG15USER}; export PGPORT=${PG15PORT}; xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' ./bin/cucumber --strict features/manage/verification.feature:31
- name: No Tasks for spec/features/manage
  scripts:
    test:
      body: echo OK
