---
tasks:
- name: features/manage/hand_over/calendar.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/hand_over/calendar.feature:7 DEFAULT_BROWSER=firefox
- name: features/manage/manage_users.feature:91
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/manage_users.feature:91 DEFAULT_BROWSER=firefox
