---
tasks:
- name: spec/features/manage/availability_calendar.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/availability_calendar.feature:7
- name: spec/features/manage/case_insensitive_inventory_code.feature:20
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/case_insensitive_inventory_code.feature:20
- name: spec/features/manage/case_insensitive_inventory_code.feature:30
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/case_insensitive_inventory_code.feature:30
- name: spec/features/manage/case_insensitive_inventory_code.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/case_insensitive_inventory_code.feature:7
- name: spec/features/manage/category_crud.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/category_crud.feature:7
- name: spec/features/manage/create_first_admin_user.feature:12
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/create_first_admin_user.feature:12
- name: spec/features/manage/create_first_admin_user.feature:4
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/create_first_admin_user.feature:4
- name: spec/features/manage/create_first_admin_user.feature:35
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/create_first_admin_user.feature:35
- name: spec/features/manage/create_first_admin_user.feature:51
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/create_first_admin_user.feature:51
- name: spec/features/manage/create_software_license.feature:51
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/create_software_license.feature:51
- name: spec/features/manage/create_software_license.feature:8
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/create_software_license.feature:8
- name: spec/features/manage/edit_user.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/edit_user.feature:7
- name: spec/features/manage/global_search.feature:11
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/global_search.feature:11
- name: spec/features/manage/global_search.feature:27
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/global_search.feature:27
- name: spec/features/manage/global_search.feature:44
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/global_search.feature:44
- name: spec/features/manage/hand_over.feature:18
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/hand_over.feature:18
- name: spec/features/manage/hand_over.feature:40
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/hand_over.feature:40
- name: spec/features/manage/hand_over.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/hand_over.feature:7
- name: spec/features/manage/inactive_inventory_pools.feature:21
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/inactive_inventory_pools.feature:21
- name: spec/features/manage/inactive_inventory_pools.feature:30
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/inactive_inventory_pools.feature:30
- name: spec/features/manage/inactive_inventory_pools.feature:40
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/inactive_inventory_pools.feature:40
- name: spec/features/manage/inactive_inventory_pools.feature:9
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/inactive_inventory_pools.feature:9
- name: spec/features/manage/inventory_search.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/inventory_search.feature:7
- name: spec/features/manage/model_crud.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/model_crud.feature:7
- name: spec/features/manage/serial_number_validation.feature:24
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/serial_number_validation.feature:24
- name: spec/features/manage/serial_number_validation.feature:41
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/serial_number_validation.feature:41
- name: spec/features/manage/serial_number_validation.feature:55
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/serial_number_validation.feature:55
- name: spec/features/manage/serial_number_validation.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/serial_number_validation.feature:7
- name: spec/features/manage/serial_number_validation.feature:69
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/serial_number_validation.feature:69
- name: spec/features/manage/serial_number_validation.feature:81
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/serial_number_validation.feature:81
- name: spec/features/manage/take_back.feature:19
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec rspec -r ./spec/steps/manage/load.rb spec/features/manage/take_back.feature:19
