---
tasks:
- name: features/manage/contract/contracts.feature:7
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/contract/contracts.feature:7 DEFAULT_BROWSER=firefox
- name: features/manage/contract/contracts.feature:16
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/contract/contracts.feature:16 DEFAULT_BROWSER=firefox
- name: features/manage/hand_over/delete.feature:24
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/hand_over/delete.feature:24 DEFAULT_BROWSER=firefox
- name: features/manage/hand_over/edit_reservation.feature:11
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/hand_over/edit_reservation.feature:11 DEFAULT_BROWSER=firefox
- name: features/manage/hand_over/sign_contract.feature:22
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/hand_over/sign_contract.feature:22 DEFAULT_BROWSER=firefox
- name: features/manage/inventory/categories.feature:27
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/inventory/categories.feature:27 DEFAULT_BROWSER=firefox
- name: features/manage/inventory/create_model_with_packages.feature:132
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/inventory/create_model_with_packages.feature:132 DEFAULT_BROWSER=firefox
- name: features/manage/inventory/edit_item.feature:103
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/inventory/edit_item.feature:103 DEFAULT_BROWSER=firefox
- name: features/manage/inventory/inventory.feature:94
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/inventory/inventory.feature:94 DEFAULT_BROWSER=firefox
- name: features/manage/inventory/option.feature:20
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/inventory/option.feature:20 DEFAULT_BROWSER=firefox
- name: features/manage/order/contract.feature:74
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/order/contract.feature:74 DEFAULT_BROWSER=firefox
- name: features/manage/order/contract.feature:93
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/order/contract.feature:93 DEFAULT_BROWSER=firefox
- name: features/manage/order/manage_orders.feature:11
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/order/manage_orders.feature:11 DEFAULT_BROWSER=firefox
- name: features/manage/take_back/edit_take_back_end_date.feature:11
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/take_back/edit_take_back_end_date.feature:11 DEFAULT_BROWSER=firefox
- name: features/manage/take_back/edit_take_back_end_date.feature:18
  scripts:
    test:
      body: |-
        set -eux
        export PATH=~/.rubies/$RUBY/bin:$PATH
        mkdir -p log
        xvfb-run -a -e log/xvfb.log --server-args='-screen 0 1920x1080x24' bundle exec cucumber -p default  --strict features/manage/take_back/edit_take_back_end_date.feature:18 DEFAULT_BROWSER=firefox
